<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\ResultSetMappingBuilder;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProductsBySearch($value)
    {
        $em = $this->getEntityManager();
        $sql = "select p.* from Product p where upper(concat(p.name,' ',p.description)) like upper('%{$value}%')
        order by name ASC";

        $rsm = new ResultSetMappingBuilder($em);
        $rsm->addRootEntityFromClassMetadata(
            \App\Entity\Product::class,
            'p'
        );
        $query = $em->createNativeQuery($sql, $rsm);
        $arrayObj = $query->getResult();

        return $arrayObj;
    }

    public function findProductsByIdCategory($id)
    {
        $em = $this->getEntityManager();
        $sql = "select 
                    p.* 
                from 
                    Product p 
                    inner join ProductCategory c on (c.id_product = p.id)
                    where 
                        c.id_category = '{$id}'
                order by p.description ASC";

        $rsm = new ResultSetMappingBuilder($em);
        $rsm->addRootEntityFromClassMetadata(
            \App\Entity\Product::class,
            'p'
        );
        $query = $em->createNativeQuery($sql, $rsm);
        $arrayObj = $query->getResult();

        return $arrayObj;
    }
}
